# Generated by Django 5.2.7 on 2025-10-28 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='populattion',
            new_name='population',
        ),
    ]
